server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:~/data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      path: /h2
      settings:
        web-allow-others: false
  jpa:
      show-sql: true
      defer-datasource-initialization: true
      hibernate:
        ddl-auto: none
        hbm2ddl:
          import_files: init.sql
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.H2Dialect
      database-platform: org.hibernate.dialect.H2Dialect
